### ISSUE TITLE
CSS affects the slider itself

### ISSUE THREAD

**Issue by ryuuart** [ryuuart/manawave#3]
Users can create custom CSS on the slider and depending on if it's a flexbox or something, it'll break. We want to make sure that CSS can't leak and affect the behavior of the slider.

**Comment by ryuuart** [comment]
Decided that we did have a restriction… that is the wrapper element must have certain styles no matter what. They are:

```css
#id {
  white-space: nowrap;
  overflow: hidden;
  
  position: relative;
}
```

There was also one bug we missed where the HTML nested children would be "flattened" to become all siblings.
